sendhut/partners/urls.py
from django.conf.urls import url

from .views import PartnerApplication, PartnerApplicationSuccess


urlpatterns = [
    url(r'^$', PartnerApplication.as_view(), name='apply'),
    url(r'^feedback$', PartnerApplicationSuccess.as_view(),
        name='application_feedback'),
]

sendhut/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

from sendhut.partners.views import SMEPackageView
from .views import (
    HomeView, AboutView, FAQView,
    PrivacyView, TermsView
)


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about-us/?$', AboutView.as_view(), name='about-us'),
    url(r'^faqs/?$', FAQView.as_view(), name='faqs'),
    url(r'^terms/?$', TermsView.as_view(), name='terms'),
    url(r'^privacy/?$', PrivacyView.as_view(), name='privacy'),
    url(r'^partners/?$', include('sendhut.partners.urls', namespace='partners')),
    url(r'^business/?$', SMEPackageView.as_view(), name='business'),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^api/?$', include('sendhut.api.urls')),
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^admin/?$', include('loginas.urls')),
]

# Change admin site title
admin.site.site_header = "Sendhut"
admin.site.site_title = "Sendhut Admin"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ]

templates/about.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="row">

  <div class="col-sm-8">
    <h4>About </h4>
    <p>
      Sendhut is reimagining the delivery experience. If you want to send a package across town or have us pick up an item, we've got you covered. Our carefully vetted and friendly couriers ensure your stuff is delivered in a fresh and timely fashion.
    </p>
    <p>
      We offer
      <ul>
        <li>Same Day </li>
        <li>Next Day </li>
        <li>Standard Delivery (1-3 business days)</li>
      </ul>
    </p>
    <p>
      The service is currently available in Lagos, with new locations being added soon. If you're outside of our service area, still share your interest — it'll help us pick our next location.
    </p>
    <p>You may also check our <a href="{% url 'faqs' %}">FAQ</a> page.</p>
    <p>
      <img class="icon" src="{% static 'images/icons/location.svg' %}" alt="">
      House A. 19 Jerry Iriabe St, Lekki Phase 1, Lagos
    </p>

  </div>

  <div class="col-sm-4" id="about-contact">
    <div>
      <h6>Get In Touch</h6>
      <p>
        <img class="icon" src="{% static 'images/icons/phone.svg' %}" alt=""> 08096699966
      </p>
      <p>
        <img class="icon" src="{% static 'images/icons/mail.svg' %}" alt="">
        <a href="mailto:hello@sendhut.com">hello@sendhut.com</a>
      </p>
    </div>
  </div>

</div>
{% endblock %}

templates/base.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Delivering Happiness">
    <meta name="author" content="Sendhut, Tade Faweya, Yao Adzaku">
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@sendhuthq" />
    <meta name="twitter:creator" content="@sendhuthq" />
    <meta property="og:url" content="sendhut.com" />
    <meta property="og:title" content="Sendhut" />
    <meta property="og:description" content="Deliver anything within Lagos, ASAP or schedule later" />
    <meta property="og:image" content="{% static 'images/icon-yellow.png' %}" />

    {% block extra_head_meta %}{% endblock %}
    <title>Sendhut | {% block title %} {{ page_title }} {% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/sendhut-icon.png' %}">
    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Organization",
      "name": "Sendhut",
      "url": "http://sendhut.com/",
      "logo": "{% static 'images/icon-yellow.png' %}",
      "sameAs": [
        "https://twitter.com/sendhuthq",
        "https://www.facebook.com/sendhuthq",
        "https://www.instagram.com/sendhuthq"
      ],
      "contactPoint": [
        {
          "@type": "ContactPoint",
          "telephone": "08096699966‬",
          "contactType": "customer service"
        },
        {
          "@type": "ContactPoint",
          "telephone": "08169567693",
          "contactType": "customer service"
        }
      ]
    }
    </script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
  </head>
  <body class="{% block body_class %}{% endblock %}">
    <div class="overlay"></div>
      {% include "partials/top_nav.html" %}
    <main role="main" class="container">
      {% include "partials/messages.html" %}
       {% block masthead %}{% endblock %}
      <div class="page-header">
        <h4 class="bold">
          {% block page_header %} {% endblock %}
        </h4>
      </div>
      <div id="content">
        {% block content %}{% endblock %}
      </div>
    </main><!--// main -->
    <div class="container-fluid">
      {% block main_bottom %}
      {% endblock %}
    </div>
    {% include "partials/footer_static.html" %}

    {% include "partials/footer.html" %}
    {% block extra_js %}{% endblock %}
    {% block extra_css %}{% endblock %}
  </body>
</html>

templates/base_email.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Simple Transactional Email</title>
    <style>
    /* -------------------------------------
        INLINED WITH htmlemail.io/inline
    ------------------------------------- */
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      .btn-primary table td:hover {
        background-color: #34495e !important;
      }
      .btn-primary a:hover {
        background-color: #34495e !important;
        border-color: #34495e !important;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

            <!-- START CENTERED WHITE CONTAINER -->
            <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;">This is preheader text. Some clients will show this text as a preview.</span>
            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Hi there,</p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Sometimes you just want to send a simple HTML email with a simple design and clear call to action. This is it.</p>
                        <table border="0" cellpadding="0" cellspacing="0" class="btn btn-primary" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;">
                          <tbody>
                            <tr>
                              <td align="left" style="font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;">
                                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;">
                                  <tbody>
                                    <tr>
                                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top; background-color: #3498db; border-radius: 5px; text-align: center;"> <a href="http://htmlemail.io" target="_blank" style="display: inline-block; color: #ffffff; background-color: #3498db; border: solid 1px #3498db; border-radius: 5px; box-sizing: border-box; cursor: pointer; text-decoration: none; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; text-transform: capitalize; border-color: #3498db;">Call To Action</a> </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">The Sendhut team</p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>

            <!-- START FOOTER -->
            <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
              <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                <tr>
                  <td class="content-block" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                    <span class="apple-link" style="color: #999999; font-size: 12px; text-align: center;">
                      Sendhut Ltd, House A, Jerry Iriabe, Off Admiralty Way, Lekki Phase 1, Lagos
                    </span>
                    <br> Don't like these emails? <a href="http://sendhut.com/settings" style="text-decoration: underline; color: #999999; font-size: 12px; text-align: center;">Unsubscribe</a>.
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->

          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

templates/business.html
{% extends "base.html" %}
{% load static %}

{% block body_class %}sme-b2b-signup{% endblock %}

{% block content %}
  <div id="sme-b2b-banner" class="card text-white text-center">
    <img class="card-img-top" src="{% static 'images/sme-b2b-banner.jpg' %}" alt="Card image cap">
    <div class="card-img-overlay">
      <h1 class="card-title">Grow your business</h1>
      <h3 class="card-text">
        You run your business, we run your deliveries.
      </h3>
    </div>
  </div>
  <br>
  <div class="row" id="sme-marketing">
    <div class="container">
      <div class="card mb-3 col-sm-4">
        <div class="card-body">
          <h4 class="card-title">Delight your customers</h4>
          <p class="card-text">
            Request and schedule deliveries at your customers' convenience.
            Choose now, or schedule a delivery for a later date.
          </p>
        </div>
      </div>

      <div class="card mb-3 col-sm-4">
        <div class="card-body">
          <h4 class="card-title">Deliver to more areas</h4>
          <p class="card-text">
            Reach customers in new neighborhoods across the city.
          </p>
        </div>
      </div>

      <div class="card mb-3 col-sm-4">
        <div class="card-body">
          <h4 class="card-title">Simple Pricing</h4>
          <p class="card-text">
            Simple pricing and flexible payments tailored for your business. Pay weekly or monthly.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="marketing-business">
    <div id="sme-request">
      <h2 class="text-center bold">Start powering your deliveries with Sendhut today</h2>
      {% include "partials/messages.html" %}
      <br>
      <div class="col-md-10 offset-md-1 bg-grey p-5 mt-2">
      <form method="post">
        {% csrf_token %}
        {% include 'partials/form.html' %}
          <div class="form-group">
            <button type="submit" class="btn btn-success">
              <span class="glyphicon glyphicon-ok"></span> Submit
            </button>
          </div>
      </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/faqs.html
{% extends "base.html" %}

{% block content %}
  <div id="faqs" class="col-sm-10">
    <h4 class="title">Frequently Asked Questions </h4>
    <ul id="faqs-menu">
      <li><a href="#q0">What are your delivery hours?</a></li>
      <li><a href="#q1">What does Sendhut deliver?</a></li>
      <li><a href="#q2">How do I get my packages to Sendhut?</a></li>
      <li><a href="#q3">Where do you deliver?</a></li>
      <li><a href="#q4">What if the customer is unavailable on delivery day?</a></li>
      <li><a href="#q5">How much does delivery cost?</a></li>
      <li><a href="#q6">How do I pay?</a></li>
      <li><a href="#q7">Can I schedule delivery in advance?</a></li>
      <li><a href="#q8">Who makes the deliveries?</a></li>
      <li><a href="#q9">What sort of drivers does Sendhut employ?</a></li>
      <li><a href="#q10">Do I have to tip? </a></li>
    </ul>

    <h4 id="q0">Answers</h4>
    <hr>
    <a class="question" id="q1">What are your delivery hours?</a>
    <p>Everyday, we deliver from 9:00 AM - 5:00 PM</p>

    <a class="question" id="q2">What does Sendhut deliver?</a>
    <p>We deliver packages of all shapes and sizes – from small items (lipstick) to gift coupons, foodstuff and large items (fridges).</p>

    <a class="question" id="q3">How do I get my packages to Sendhut?</a>
    <p>Our couriers will pickup the items from your home or office and deliver the items.
      You can also drop the items at our offices</p>

    <a class="question" id="q4">Where do you deliver?</a>
    <p>
      We currently deliver within Lagos only, with new locations being added soon. If you're outside of our service area, still share your interest — it'll help us pick our next location.
    </p>

    <a class="question" id="q5">What if the customer is unavailable on delivery day?</a>
    <p>We will reschedule the delivery for another date</p>

    <a class="question" id="q6">How much does delivery cost?</a>
    <p>Our pricing is simple. Delivery fees are based on the distance between pickup and dropoff locations, and the size and nature of the item.</p>

    <a class="question" id="q7">How do I pay?</a>
    <p>
      Pay by cash, credit card or Sendhut Credits - the choice is yours. In some cases, we may accept cash on delivery. If you make more than 50 deliveries in a week, we can offer you a weekly payment plan.
    </p>

    <a class="question" id="q8">Can I schedule delivery in advance?</a>
    <p>Yes! You can schedule for up to 3 days ahead</p>

    <a class="question" id="q9">Who makes the deliveries?</a>
    <p>Sendhut's fleet of drivers will deliver your items. Our driver couriers are highly experienced, yet undergo a thorough training process prior to handling orders.
    </p>

    <a class="question" id="q10"> Do I have to tip?</a>
    <p>This is completely up to you. Our riders make the magic happen, so tips are appreciated but  not required. Riders receive 100% of all tips.
    </p>
  </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block body_class %}body-home{% endblock %}

{% block masthead %}{% endblock %}

{% block page_header %} {% endblock %}

{% block content %}
<div class="masthead-wrapper-plain" id="app-wrapper"><!-- masthead -->
  <div class="col-md-6">
    <div id="pitch" class="hero">
      <h2 class="hero-title">Delivery</h2>
      <h2 class="hero-title" id="hero-title-dynamic">done right</h2>
      <ul class="hero-text">
        <li><img class="icon" src="{% static 'images/icons/flash.svg' %}" alt="">Want it delivered ASAP? Done!</li>
        <li><img class="icon" src="{% static 'images/icons/calendar.svg' %}" alt=""> Want it delivered tomorrow afternoon? No problem</li>
      </ul>
      <div class="download-btns">
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="https://play.google.com/store/apps/details?id=com.sendhut" target="_blank">
              <img src="{% static 'images/google-play.svg' %}" class="download-icon" alt="">
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://itunes.apple.com/au/app/sendhut/id1450266610" target="_blank">
              <img src="{% static 'images/app-store.svg' %}" class="download-icon" alt="">
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-4" id="app-preview"></div>

</div> <!--//hero -->
<br><br>
<div class="row" id="benefits"> <!-- marketing -->
  <div class="col-md-4 benefit">
    <h6 class="bold"><img class="icon" src="{% static 'images/icons/clock.svg' %}"/>At your service, Monday - Saturday</h6>
    <p>Request and schedule deliveries at your customers’ convenience. Choose now,
      or schedule a delivery for a later date</p>
  </div>
  <div class="col-md-4 benefit">
    <h6 class="bold"><img class="icon" src="{% static 'images/icons/heart.svg' %}"/> Your Happiness, Guaranteed
    </h6>
    <p>If you’re not satisfied with the quality of the service, we’ll work to make it right. Our friendly customer service team are available 24 hours a day, 7 days a week.</p>
  </div>
  <div class="col-md-4 benefit">
    <h6 class="bold"><img class="icon" src="{% static 'images/icons/text.svg' %}"/> Reduce costs</h6>
    <p>Manage all your deliveries from one spot, where you can see spending and your customer address book.</p>
  </div>
</div> <!--//marketing -->
{% endblock %}

{% block main_bottom %}
<div class="row" id="ride-estimate"></div> <!--//estimate -->

<div class="row" id="fleet-strip"> <!-- fleet -->
  <div class="col-md-5 offset-md-1">
    <img src="{% static 'images/new/IMG_1051.jpg' %}" width="400px" class="img-fluid"/ id="fleet-pic">
  </div>
  <div class="col-md-5">
    <h3 class="bold">Our drivers</h3>
    <p>
      Our couriers are carefully vetted and receive extensive training to ensure <b>your delivery arrives in style</b>. We have the right ride for your product. Our delivery fleet includes motorbikes and cars.
    </p>
    <p>
      And you can <b>track deliveries in real time</b>, from start to finish.
    </p>
    <div>
      <br>
      <h6 class="bld">Got a vehicle?</h6>

      <a href="{% url 'partners:apply' %}">
        <button type="button" class="btn btn-primary btn-md">Partner with Sendhut</button>
      </a>
    </div>
  </div>
</div> <!--//fleet -->

<div class="row" id="testimonials-wrapper">
  <div class="col-md-10 offset-md-1">
    <div class="row" id="customers"> <!-- customers -->
      <div class="col-md">
        <div class="text-center">
          <h3 class="bold">Our customers ❤️ us</h3>
          <h5>Businesses rely on Sendhut to solve their local delivery needs</h5>
        </div>

        <div class="row customer-quotes">
          <div class="customer-quote col-lg">
            <div class="card">
              <div class="card-body">
                <p class="card-text">
                  Started outsourcing my deliveries because it was hard
                  managing my own dispatch riders. Sendhut saves me time and money so I can focus on my business.
                </p>
              </div>
            </div>
            <div class="row customer-info">
              <div class="col-md-4">
                <img src="{% static 'images/5kshop.jpg' %}" class="rounded-circle">
              </div>
              <div class="col-md-8">
                <div class="customer-name">Sophia Ike-Onu</div>
                <a href="https://www.instagram.com/the5kshop/" target="_blank">
                  The 5K shop</a>
              </div>
            </div>
          </div>

          <div class="customer-quote col-lg offset-lg-1">
            <div class="card">
              <div class="card-body">
                <p class="card-text">
                  I use Sendhut to deliver my cakes and other items within Lagos.
                  Items arrive fresh and on time. Their drivers are always friendly. Very happy with the service!
                </p>
              </div>
            </div>
            <div class="row customer-info">
              <div class="col-md-4">
                <img src="{% static 'images/voilabakehouse.jpg' %}" class="rounded-circle">
              </div>
              <div class="col-md-8">
                <div class="customer-name">Amaka</div>
                <a href="http://instagram.com/voilabakehouse" target="_blank">
                  Voila Bakehouse</a>
              </div>
            </div>
          </div>

          <div class="customer-quote col-lg offset-lg-1">
            <div class="card">
              <div class="card-body">
                <p class="card-text">
                  Sendhut allows me to deliver to customers at home or office.
                  My things are nicely packaged, plus they handle returns and collect payments.
                  Great customer service.
                </p>
              </div>
            </div>
            <div class="row customer-info">
              <div class="col-md-4">
                <img src="{% static 'images/ashabee.jpg' %}" class="rounded-circle">
              </div>
              <div class="col-md-8">
                <div class="customer-name">Ashabee</div>
                <a href="https://www.instagram.com/makeupbyashabee" target="_blank">
                  MakeUpByAshabee</a>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div> <!--//customers -->
  </div>

  <div class="footer-try container-fluid">
    <div class="row">
      <div class="col-md-5 offset-md-4">
        <h3 class="bold">Try Sendhut Today</h3>
        Manage your deliveries and payments on the go.
        <div class="download-btns">
          <ul class="list-inline">
            <li class="list-inline-item">
              <a href="https://play.google.com/store/apps/details?id=com.sendhut" target="_blank">
                <img src="{% static 'images/google-play.svg' %}" class="download-icon" alt="">
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://itunes.apple.com/au/app/sendhut/id1450266610" target="_blank">
                <img src="{% static 'images/app-store.svg' %}" class="download-icon" alt="">
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/privacy.html
{% extends "base.html" %}

{% block content %}
  <div class="col-sm-10">
    <h4>Privacy policy</h4>
    <h6>Privacy Policy</h6>
    <p>
      Sendhut may collect personal information to help you place and receive delivery
      orders and to improve the services we offer to you.
      We think it's only right that you're clear on (and comfortable with) how
      the information you share is used and safeguarded:

      <ul>
        <li>We work hard to ensure it's totally secure</li>
        <li>We use it to make our service as good as it can be</li>
        <li>We won't sell it to anyone – ever </li>
      </ul>
    </p>

    <p>We may update the policy from time to time (most likely only with small changes),
      so we suggest you check back here every now and then to ensure you're still satisfied.
      Don't worry, we'll let you know if we make any major updates.
      The version you see below was last modified on 22 January 2018.
    </p>

    <h6 class="bold">Information that we collect from you</h6>

    We collect two sorts of information:

    <ol>
      <li>
        Personal information that you provide
        <p>
          When you visit, make orders, search within, fill contact forms, respond
          to surveys or register on our website, as appropriate, you provide us with
          information about yourself including name, contact details and payment information,
          including credit card information and delivery address used to complete the purchase transaction. Furthermore, we collect order related information which includes items purchased,
          date and time of item purchase, special order information or instruction with the order/delivery.</p>
          <p>
            By accessing our web platforms, we may also receive and store certain information about you,
            your devices or your use of our service automatically when you access SendHut. This information may include:
            <ol>
              <li>	location data and certain characteristics of, and performance data about the device you use to access our Services </li>
              <li>	carrier/operating system including device and connection type, IP address, web browser
                and mobile payment methods; and</li>
                <li>specific SendHut pages you visit, content you view, features you use and the date and time of your visits </li>
            </ol>
          </p>
      </li>
      <li>
        <p> Cookies </p>
        <p>
          Cookies are small files which are stored on your computer when you visit websites like ours.
        </p>

        We use cookies to:

        <ul>
          <li>'remember' you and improve your experience of this website.</li>
          <li>Help remember and process the items in the shopping cart.</li>
        </ul>
        <br>
        <p>
          If you turn cookies off, you'll be treated as a ‘first-time' visitor when you return to the site and
          some of the features that make your site experience more efficient may not function properly.
        </p>
      </li>
    </ol>

    <h6>How do we use your information? </h6>

    All information provided to us will be stored on our database and used in the following ways

    <ul>
      <li>	To offer support, improve and develop our business and services to you</li>
      <li>Remembering your preferences allows us to tailor that experience to your needs, likes and dislikes.</li>
      <li>Process your order with partner and connect you to a delivery officer, and in turn complete your deliveries</li>
      <li>To contact you in connection with your orders and deliveries </li>
    </ul>

    <p>
      In the event of sale, transfer, merger, reorganization, dissolution, or similar event we may transfer your information to one or more third parties as part of that transaction.
    </p>

    <h6> How do we protect it?</h6>

    <p>
      We take your privacy seriously. We're committed to ensuring that the information you provide is kept secure at all times, and we have a series of physical, electronic and managerial procedures in place to prevent unauthorised access. Our website is scanned on a regular basis for security holes and known vulnerabilities in order to make your visit to our site as safe as possible.
    </p>

    <p>
      Remember, though, that we can only control the information that's collected through our own website. Sometimes we may link to other sites which we think may be of interest – any information you share on these sites will be outside of our control. They'll have their own privacy and cookie policies, so we suggest you take a look.</p>


      <h6>Want to find out more?</h6>
    <p>
      If you've got any questions, concerns or feedback about what you've read in this policy, get in touch – we'd love to hear how we're doing.</p>
  </div>
{% endblock %}